# Generated by Django 2.2.10 on 2021-03-05 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(choices=[('ludhiana', 'LUDHIANA'), ('chandigarh', 'CHANDIGARH')], default='ludhiana', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('schoolbag', 'SCHOOLBAG'), ('handbag', 'HANDBAG'), ('travellingbag', 'TRAVELLINGBAG')], default='schoolbag', max_length=20)),
                ('stock', models.CharField(default='10000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('city', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('location', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
    ]
