# Generated by Django 2.2.10 on 2021-03-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210305_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(choices=[('school bag', 'SCHOOLBAG'), ('hand bag', 'HANDBAG'), ('travelling bag', 'TRAVELLINGBAG')], default='schoolbag', max_length=20),
        ),
    ]
