# Generated by Django 2.2.10 on 2021-03-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210306_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(choices=[('school bag', 'SCHOOL BAG'), ('hand bag', 'HAND BAG'), ('travelling bag', 'TRAVELLING BAG')], default='schoolbag', max_length=20),
        ),
    ]
