name: Frappe Linter
on:
  pull_request:
    branches:
      - develop
      - version-12-hotfix
      - version-11-hotfix
jobs:
  check_translation:
    name: Translation Syntax Check
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup python3
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Validating Translation Syntax
      run: |
        git fetch origin $GITHUB_BASE_REF:$GITHUB_BASE_REF -q
        files=$(git diff --name-only --diff-filter=d $GITHUB_BASE_REF)
        python $GITHUB_WORKSPACE/.github/helper/translation.py $files
