const ACTIVATE_INTERN = "ACTIVATE_INTERN";
const DEACTIVATE_INTERN = "DEACTIVATE_INTERN";
const LEAVE_INTERN = "LEAVE_INTERN";
const SET_ROLE = "SET_ROLE";

export { ACTIVATE_INTERN, DEACTIVATE_INTERN, LEAVE_INTERN, SET_ROLE };
